package com.wael.astimal.pos.features.inventory.data.remote.dto

import com.wael.astimal.pos.core.util.Clock
import com.wael.astimal.pos.core.util.parseIsoTimestamp
import com.wael.astimal.pos.features.inventory.data.entity.CategoryEntity
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents the "data" object within the categories API response.
 */
@Serializable
data class CategorySyncData(
    val categories: List<CategoryDto>,
    @SerialName("date")
    val nextSyncDate: String
)

/**
 * Represents a single category object from the API.
 */
@Serializable
data class CategoryDto(
    val id: Long,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    val name: String, // Default name
    val translations: List<TranslationDto>
)

/**
 * Maps a CategoryDto from the network to our local database CategoryEntity.
 */
fun CategoryDto.toEntity(): CategoryEntity {
    val arName = translations.find { it.locale == "ar" }?.name
    val enName = translations.find { it.locale == "en" }?.name

    return CategoryEntity(
        serverId = this.id,
        // The localId will be auto-generated by Room if it's a new entry.
        localId = 0L,
        arName = arName,
        enName = enName ?: this.name, // Fallback to default name
        updatedAt = this.updatedAt.parseIsoTimestamp() ?: Clock.now(),
        createdAt = this.createdAt.parseIsoTimestamp() ?: Clock.now()
    )
}
